In [1]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd


In [2]:
missing_values = ["n/a", "na", "--",".","NaN"]
dataset = pd.read_csv("openrefine/TrainingAll.csv", na_values = missing_values)
##dataset.fillna(-1)

In [3]:
print(dataset.columns.values)

['File' 'NUID' 'SATREAD' 'SATMATH' 'ACTCUM' 'CARNIGIE' 'AVGSALMALE'
 'AVGSALWOM' 'AVGSALTOT' 'HOUSE' 'HDEM' 'HREP' 'SENATE' 'SDEM' 'SREP'
 'PERNWHT' 'STUFACR' 'TUITINS' 'FEEINS' 'TUITOUT' 'FEEOUT' 'FOOTBALL'
 'TUITPER' 'SLCTVTY' 'APPEAL' 'RSRCHPSTU' 'HIGHBP' 'CHGENROL' 'FRACDEGRE'
 'RETPCNT' 'BINGEDRK' 'HEALTHINS' 'MENTALHLTH' 'PHYSHLTH']


In [4]:
dataset.describe()

NUID      SATREAD      SATMATH       ACTCUM     CARNIGIE  \
count  5815.000000  3953.000000  3982.000000  4076.000000  5815.000000   
mean   4157.673603   577.232482   584.517830    25.554711    18.493035   
std    2373.582385    70.693090    74.392781     3.475093     5.848469   
min      10.000000   315.000000   325.000000     9.000000    -3.000000   
25%    2187.000000   530.000000   531.500000    23.000000    18.000000   
50%    4119.000000   570.000000   570.000000    25.000000    19.000000   
75%    6146.000000   620.000000   620.000000    28.000000    22.000000   
max    9257.000000   800.000000   800.000000    35.000000    32.000000   

         AVGSALMALE     AVGSALWOM     AVGSALTOT        HOUSE         HDEM  \
count   5753.000000   5621.000000   5815.000000  5223.000000  5223.000000   
mean    7611.038415   6956.482476   7262.975924     0.133001    -0.962480   
std     2563.514247   1961.291246   2332.068718     0.813477     0.395875   
min      777.000000    543.000000    748.000000    -1.308000    -1.902000   
25%     5979.000000   5713.000000   5804.500000    -0.858000    -1.189000   
50%     7391.000000   6766.000000   7059.000000     0.540000    -0.995000   
75%     8934.000000   8025.000000   8482.500000     0.796000    -0.669000   
max    22798.000000  20266.000000  22146.000000     1.228000     0.136000   

       ...       APPEAL     RSRCHPSTU       HIGHBP     CHGENROL    FRACDEGRE  \
count  ...  5808.000000   5586.000000  1204.000000  5815.000000  5815.000000   
mean   ...     0.778145   1269.270273    32.695847     1.000459     0.204678   
std    ...     2.758643   4551.670027     4.831909     0.089779     0.071505   
min    ...     0.000000      0.000000    22.600000     0.142015     0.000000   
25%    ...     0.229934      0.000000    29.175000     0.975602     0.164728   
50%    ...     0.343800      0.617348    32.300000     1.000000     0.200536   
75%    ...     0.594316    370.478604    35.200000     1.016784     0.236112   
max    ...    68.600000  77304.309710    47.800000     2.653455     0.901734   

           RETPCNT     BINGEDRK    HEALTHINS   MENTALHLTH     PHYSHLTH  
count  5815.000000  1195.000000  1195.000000  1195.000000  1195.000000  
mean     74.992261    16.842929    17.032971    12.962092    13.131381  
std      14.048816     2.738608     5.672745     1.906480     2.247178  
min       0.000000     9.600000     4.100000     8.100000     7.400000  
25%      68.000000    14.900000    13.050000    11.700000    11.800000  
50%      76.000000    16.600000    16.500000    13.000000    13.100000  
75%      84.000000    18.700000    19.900000    14.100000    14.500000  
max     100.000000    25.400000    39.500000    18.200000    20.400000  

[8 rows x 33 columns]

In [5]:
#list of collums
collist = dataset.columns.tolist()


In [72]:
from sklearn import preprocessing
from sklearn.impute import SimpleImputer

robust_scaler = preprocessing.RobustScaler()
np_scaled = robust_scaler.fit_transform(dataset[collist[1:]])

fill_Nan = SimpleImputer(missing_values = np.nan, strategy ="constant", fill_value = -50.0)
np_imp = fill_Nan.fit_transform(np_scaled)
dataset_scaled = pd.DataFrame(np_imp)

# create the Labelencoder object
le = preprocessing.LabelEncoder()
dataset["File"] = le.fit_transform(dataset["File"])
dataset["File"].unique()

#merge the two dataframes
dataset_scaled["33"] = dataset["File"]
dataset_scaled.head(4)



0         1         2    3     4         5         6         7  \
0 -0.830765 -1.333333 -1.355932 -1.2 -0.25  0.015905 -0.086073  0.007468   
1  0.179338  0.777778  0.903955  0.6 -1.00  1.257191  1.030709  1.161688   
2  0.063400 -1.000000 -1.016949 -1.2 -0.25 -0.151946 -0.237889 -0.187453   
3  0.734024  0.555556  0.790960  1.0 -0.75  1.162437  0.565311  0.950709   

          8         9  ...         24         25   26        27      28    29  \
0  0.159008  1.001923  ...   3.852740 -50.000000  0.0 -0.690035 -0.8125 -50.0   
1  0.159008  1.001923  ...  33.957799   2.257261  0.0  0.076951  0.2500 -50.0   
2  0.159008  1.001923  ...   0.815154   1.377593  0.0 -1.111355 -0.8750 -50.0   
3  0.159008  1.001923  ...   4.010456   1.278008  0.0 -0.103113  0.6875 -50.0   

     30    31    32  33  
0 -50.0 -50.0 -50.0   0  
1 -50.0 -50.0 -50.0   0  
2 -50.0 -50.0 -50.0   0  
3 -50.0 -50.0 -50.0   0  

[4 rows x 34 columns]

In [7]:
target_cols = ["CHGENROL","FRACDEGRE","RETPCNT"]
col_index = [dataset.columns.get_loc(name) for name in target_cols]
for index,col in enumerate(col_index):
    col_index[index] = col - 1
col_index

[26, 27, 28]

In [8]:
#drop the seperate the data into targets and data

cols = [col for col in dataset_scaled.columns if col not in col_index]
X = dataset_scaled[cols]
y = dataset_scaled[col_index]

In [9]:
y.describe()

26           27           28
count  5815.000000  5815.000000  5815.000000
mean      0.011153     0.058023    -0.062984
std       2.180071     1.001699     0.878051
min     -20.834068    -2.809255    -4.750000
25%      -0.592448    -0.501636    -0.500000
50%       0.000000     0.000000     0.000000
75%       0.407552     0.498364     0.500000
max      40.150127     9.822873     1.500000

In [10]:
des = X.columns[18:]
X[des].describe()

18           19           20           21           22  \
count  5815.000000  5815.000000  5815.000000  5815.000000  5815.000000   
mean     -1.216221    -0.974663   -34.675497    -3.440900     2.407860   
std       7.969908     8.154346    23.058379    12.756397    27.925353   
min     -50.000000   -50.000000   -50.000000   -50.000000   -50.000000   
25%      -0.492232    -0.457143   -50.000000    -0.564879    -0.536107   
50%      -0.041430    -0.030415   -50.000000    -0.081886    -0.000693   
75%       0.521662     0.549770    -0.596250     0.496052     0.465620   
max       1.892762    29.083871     1.250000     7.468984  1219.202043   

                23           24           25           29           30  \
count  5815.000000  5815.000000  5815.000000  5815.000000  5815.000000   
mean      1.130381     1.320462   -39.633860   -39.711712   -39.708860   
std       7.771664    15.905665    20.291256    20.233643    20.240094   
min     -50.000000   -50.000000   -50.000000   -50.000000   -50.000000   
25%      -0.313300    -0.001666   -50.000000   -50.000000   -50.000000   
50%      -0.001050    -0.001666   -50.000000   -50.000000   -50.000000   
75%       0.686290     0.883945   -50.000000   -50.000000   -50.000000   
max     187.320739   208.658993     2.572614     2.315789     3.357664   

                31           32           33  
count  5815.000000  5815.000000  5815.000000  
mean    -39.728095   -39.722461     1.499570  
std      20.201998    20.213389     1.118361  
min     -50.000000   -50.000000     0.000000  
25%     -50.000000   -50.000000     0.000000  
50%     -50.000000   -50.000000     2.000000  
75%     -50.000000   -50.000000     2.000000  
max       2.166667     2.703704     3.000000

In [11]:
from sklearn.model_selection import cross_val_predict, cross_val_score, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler

In [1]:
def rfr_model(X, y):
# Perform Grid-Search
    gsc = GridSearchCV(
        estimator=RandomForestRegressor(),
        param_grid={
            'max_depth': range(10,50,5),
            'n_estimators': (10, 50, 100, 1000,2000,3000),
        },
        cv=5, scoring='neg_mean_squared_error', verbose=0, n_jobs=-1)
    
    grid_result = gsc.fit(X, y)
    best_params = grid_result.best_params_
    
    rfr = RandomForestRegressor(max_depth=best_params["max_depth"], n_estimators=best_params["n_estimators"],                               random_state=False, verbose=False)
# Perform K-Fold CV
    ##scores = cross_val_score(rfr, X, y, cv=10, scoring='neg_mean_absolute_error')
    ##predictions = cross_val_predict(rfr, X, y, cv=10)
    #return (scores,predictions,rfr)
    return rfr, best_params

In [16]:
rfr, best_params = rfr_model(X,y)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 36 concurrent workers.
[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  2.9min
[Parallel(n_jobs=-1)]: Done 240 out of 240 | elapsed: 12.9min finished


In [22]:
#y_p = predictions

In [21]:
#y_t = y.values
#y_t

array([[ 0.        , -0.69003459, -0.8125    ],
       [ 0.        ,  0.07695104,  0.25      ],
       [ 0.        , -1.11135496, -0.875     ],
       ...,
       [ 2.24296736, -0.33713021, -0.5625    ],
       [11.15232775, -1.11483109, -0.5       ],
       [ 0.45127282,  0.50315488,  0.        ]])

In [23]:
#y_t.shape

(5815, 3)

In [24]:
#y_p.shape

(5815, 3)

In [25]:
#def RMSE(targets, predictions):
 #   return np.sqrt(np.mean((predictions-targets)**2))

In [48]:
RMSE(y_t,y_p)

1.3559325964910205

In [80]:
np_scaled_2 = np_scaled.copy()
np_unscaled = robust_scaler.inverse_transform(np_scaled)

np_scaled_2[:,26:29] = y_p
np_unscaled_p = robust_scaler.inverse_transform(np_scaled_2)

In [81]:
y_t_unsc = np_unscaled[:,26:29]
#y_p_unsc = np_unscaled_p[:,26:29]
#y_p_unsc[0:10,:]

In [82]:
y_t_unsc

array([[ 1.        ,  0.1512788 , 63.        ],
       [ 1.        ,  0.20602944, 80.        ],
       [ 1.        ,  0.12120319, 62.        ],
       ...,
       [ 1.09236948,  0.17647059, 67.        ],
       [ 1.45927315,  0.12095504, 68.        ],
       [ 1.01858424,  0.23645365, 76.        ]])

In [83]:
y_p_unsc

array([[ 0.9981464 ,  0.14888452, 64.54794906],
       [ 1.01011038,  0.20357504, 82.89733333],
       [ 0.99901481,  0.13990335, 63.28880216],
       ...,
       [ 1.2620749 ,  0.09643621, 80.39233333],
       [ 1.15970869,  0.1742675 , 71.957     ],
       [ 1.03334625,  0.21332011, 74.37733333]])

In [84]:
RMSE(y_t_unsc, y_p_unsc)

5.341162321550086